trigger:
  branches:
    include:
    - none
variables:
- name: dockerRegistryServiceConnection
  value: '4fe42d65-c2fa-4faf-99b5-0f6cedda9590'
- name: imageRepository
  value: 'ekartshopping'
- name: containerRegistry
  value: 'testdemoreg.azurecr.io'
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/docker/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
pool:
  name: 'demo'
stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download build artifact from CI pipeline'
      inputs:
        buildType: 'specific'
        project: '28587c37-914e-41c8-afe4-c42d5bcf83c1'
        pipeline: '6'
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Build.SourcesDirectory)/target'
    - task: Bash@3
      displayName: 'Move artifact JAR to target folder'
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p $(Build.SourcesDirectory)/target
          cp $(Build.SourcesDirectory)/target/drop/*.jar $(Build.SourcesDirectory)/target/
          echo "Contents of target folder:"
          ls -l $(Build.SourcesDirectory)/target
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: 'testdemoreg'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: 'docker/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          latest
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'testdemoreg'
        command: 'login'

